name: Run terrafirm integration tests

on:
  # Run on demand
  workflow_dispatch:

  # Run on pull request review with a specific command
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: contains(github.event.review.body, '/build') || github.event_name == 'workflow_dispatch'
    outputs:
      run-id: ${{ steps.trigger.outputs.run-id }}
    steps:
      - name: Set terrafirm run-id
        id: trigger
        run: |
          RUN_ID=$(uuidgen)
          echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
          echo "RUN_ID=${RUN_ID}"

  test-source:
    runs-on:
      - codebuild-p3-terrafirm-${{ github.run_id }}-${{ github.run_attempt }}
        instance-size:small
    needs: trigger
    strategy:
      fail-fast: false
      matrix:
        source-build: [rhel8, rhel9, win16, win19, win22]
    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_aws_region: us-east-1
      TF_VAR_codebuild_id: ${{ needs.trigger.outputs.run-id }}
      TF_VAR_source_builds: '["${{ matrix.source-build }}"]'
      TF_VAR_standalone_builds: '[]'
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Terrafirm integration tests
        id: terrafirm
        uses: ./.github/actions/test
        with:
          destroy-after-test: true

  test-standalone:
    runs-on:
      - codebuild-p3-terrafirm-${{ github.run_id }}-${{ github.run_attempt }}
        instance-size:small
    needs: trigger
    strategy:
      fail-fast: false
      matrix:
        standalone-build: [rhel8, rhel9, win16, win19, win22]
    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_VAR_aws_region: us-east-1
      TF_VAR_codebuild_id: ${{ needs.trigger.outputs.run-id }}
      TF_VAR_source_builds: '[]'
      TF_VAR_standalone_builds: '["${{ matrix.standalone-build }}"]'
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Terrafirm integration tests
        id: terrafirm
        uses: ./.github/actions/test
        with:
          destroy-after-test: true
